language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.0 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - wp plugin install wordpress-importer --activate
  - git clone https://github.com/manovotny/wptest.git
  - sed -i'' 's/read\ WPPATH/let\ WPPATH=\"\/tmp\/wordpress\"/' wptest/wptest-cli-install.sh
  - bash wptest/wptest-cli-install.sh

script: phpunit
